let recipes = [
    {
        id: 1,
        name: "Grandma Lenon's Chocolate Chip Cookies",
        recipe_img: "",
        time_total: '40',
        time_type: 'min',
        time_label: 'Total Time',
        yield: '6',
        yield_type: 'dozen',
        yield_label: 'Yield',
        prep_time: '30',
        prep_type: 'min',
        prep_label: 'Prep Time',
        cook_time: '10',
        cook_type: 'min',
        cook_label: 'Cook Time',
        temp: '350',
        temp_symbol: '°',
        temp_label: 'Temperature',
        cuisine: 'Mexican',
        course: 'Dessert',
        skill_level: 'Beginner',
        pdf: 'pdf.pdf',
        recipe_blurb: "My Mom has been making these since I was a child. They are still my very favorite over 50 year later. I hope you love them as much as I do!",
        ingredients: [
                    '2 cups shortening',
                    '2 cups sugar',
                    '1 cup brown sugar',
                    '4 eggs',
                    '4 cups flour',
                    '2 teaspoons salt',
                    '2 teaspoons baking soda',
                    '4 teaspoons vanilla',
                    '1 bag of chocolate chips'
                    ],
        serving_size: '1 Cookie',
        total_servings: '72',
        calories: '114',
        carbohydrates: '12',
        total_fat: '7',
        sodium: '85',
        protein: '1',
        sugar: '7',     
        instructions: [
                    'Cream shortening, add sugar gradually and cream.',
                    'Add eggs and mix.',
                    'Sift flour once, then measure and add salt, soda and sift again.',
                    'Add flour in 4 parts and mix well.',
                    'Lastly add vanilla and chocolate chips and mix well.',
                    'Scoop out nice portions onto a greased cookie sheet and bake.',
                    ],
        tips_var: [
                    'Bla Bla Bla',
                    'Bla Bla Bla',
                    'Bla Bla Bla',
                    'Bla Bla Bla'
                    ],
        tags:       [
                    'cookie',
                    'chocolate'
                    ],
    },
    {
        id: 2,
        name: "Uncle Darin's Pico De Gallo",
        recipe_img: "",
        time_total: '15',
        time_type: 'min',
        time_label: 'Total Time',
        yield: '3-4',
        yield_type: 'cups',
        yield_label: 'Yield',
        prep_time: '10',
        prep_type: 'min',
        prep_label: 'Prep Time',
        cook_time: '5',
        cook_type: 'min',
        cook_label: 'Wait Time',
        temp: null,
        temp_alt: "Don't Cook",
        temp_label: null,
        cuisine: 'Mexican',
        course: 'Side Dish',
        skill_level: 'Beginner',
        pdf: 'pdf.pdf',
        recipe_blurb: "My Mom has been making these since I was a child. They are still my very favorite over 50 year later. I hope you love them as much as I do!",
        ingredients: [
                    '3-4 medium size ripe tomatoes',
                    '1/3 medium size onion',
                    '6 sprigs cilantro',
                    '3 cloves of garlic',
                    '1 tsp garlic salt',
                    '2 Tbsp lemon juice',
                    '1/3 to 1 jalapeno (to your taste)'
                    ],
        serving_size: '1/2 Cup',
        total_servings: '8',
        calories: '19',
        carbohydrates: '3',
        total_fat: '0',
        sodium: '249',
        protein: '1',
        sugar: '2',     
        instructions: [
                    'Chop garlic and jalapenos into fine pieces (1/16-1/8” chunks).',
                    'Then chop the remaining ingredients to whatever size you desire.',
                    'Then place all of the ingredients into a bowl and mix very well.',
                    'Let sit for 5 minutes and serve with tortilla chips.'
                    ],
        tips_var: [
                    'I typically use a chopper to make my pico, so I always chop the garlic and jalapenos first to ensure that they are chopped to my liking. Next, I add the cilantro and onions and chop again. Lastly, I add the tomatoes to the mixture and chop once more, so that those chunks are bigger than the rest. Enjoy!'
                    ],
        tags:       [
                    'garlic',
                    'tomatoes',
                    'cilantro',
                    'salsa',
                    'topping'
                    ],
    },
    {
        id: 3,
        name: "Grandma Lenon's Chocolate Chip Cookies",
        recipe_img: "",
        time_total: '40',
        time_type: 'min',
        yield: '6',
        yield_type: 'dozen',
        prep_time: '30',
        prep_type: 'min',
        cook_time: '10',
        cook_type: 'min',
        temp: '350',
        cuisine: 'Mexican',
        course: 'Dessert',
        skill_level: 'Beginner',
        pdf: 'pdf.pdf',
        recipe_blurb: "My Mom has been making these since I was a child. They are still my very favorite over 50 year later. I hope you love them as much as I do!",
        ingredients: [
                    '2 cups shortening',
                    '2 cups sugar',
                    '1 cup brown sugar',
                    '4 eggs',
                    '4 cups flour',
                    '2 teaspoons salt',
                    '2 teaspoons baking soda',
                    '4 teaspoons vanilla',
                    '1 bag of chocolate chips'
                    ],
        serving_size: '1 Cookie',
        total_servings: '72',
        calories: '114',
        carbohydrates: '12',
        total_fat: '7',
        sodium: '85',
        protein: '1',
        sugar: '7',     
        instructions: [
                    'Cream shortening, add sugar gradually and cream.',
                    'Add eggs and mix.',
                    'Sift flour once, then measure and add salt, soda and sift again.',
                    'Add flour in 4 parts and mix well.',
                    'Lastly add vanilla and chocolate chips and mix well.',
                    'Scoop out nice portions onto a greased cookie sheet and bake.',
                    ],
        tips_var: [
                    'Bla Bla Bla',
                    'Bla Bla Bla',
                    'Bla Bla Bla',
                    'Bla Bla Bla'
                    ],
        tags:       [
                    'cookie',
                    'chocolate'
                    ],
    }
]